# Generated by Django 6.0.2 on 2026-02-20 20:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('caja_ahorro', 'Caja de Ahorro'), ('cuenta_corriente', 'Cuenta Corriente'), ('plazo_fijo', 'Plazo Fijo')], max_length=30)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('moneda', models.CharField(choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares')], default='PYG', max_length=5)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('bloqueada', 'Bloqueada'), ('cerrada', 'Cerrada')], default='activa', max_length=20)),
                ('limite_transferencia_diaria', models.DecimalField(decimal_places=2, default=10000000, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='clients.client')),
            ],
        ),
    ]
