# Generated by Django 6.0.2 on 2026-02-20 20:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_transaccion', models.CharField(choices=[('interna', 'Transferencia Interna'), ('externa', 'Transferencia Externa')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares')], max_length=5)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('reversada', 'Reversada')], default='pendiente', max_length=20)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_destino', to='accounts.account')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='accounts.account')),
            ],
        ),
    ]
