# Generated by Django 6.0.2 on 2026-02-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='numero_cuenta_externa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
