# Generated by Django 6.0.2 on 2026-02-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_transaction_numero_cuenta_externa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cuenta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='accounts.account'),
        ),
    ]
