# Generated by Django 6.0.2 on 2026-02-24 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('transactions', '0003_alter_transaction_cuenta_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='banco_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='banks.bank'),
        ),
    ]
